// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgvgxeotkaywrnjaorzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFndmd4ZW90a2F5d3JuamFvcnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDc3NjYsImV4cCI6MjA3MzU4Mzc2Nn0.7H2X6Zvdq6VsmmrolqMvmqhnqD3D2mn1omq78GkmDso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});